### ISSUE TITLE
task: Simplify the UX of the docs further.

### ISSUE THREAD

**Issue by 0xSilkweave** [Merit-Circle/beam-docs#39]
The Main entry page at https://docs.onbeam.com/ is currently very dev-focused (passing API key, managing assets, etc.) whilst the 'Chain' page (https://docs.onbeam.com/chain) is fairly hidden from sight (top-right, small). Clicking on 'Getting Started' so far only makes sense to developers as it leads to the SDK / Services page (https://docs.onbeam.com/service), but not to anyone else e.g. the end-user who would want to enjoy the actual dApps or the Beam chain without having much technological knowledge.

I feel the main 'Chain' page (https://docs.onbeam.com/chain) should be the default facing page one should be greeted with, which then should have sections for users, developers, third parties, and so on.

**Comment by 0x0sub** [comment]
Thanks for your feedback. We've applied a temporary update to guide different types of users to the corresponding sections. A more comprehensive rework of the page will occur at a later date.
